/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;
using System.IO;
using Moduino.node;

namespace Moduino.lexer {

internal class PushbackReader {
  private TextReader reader;
  private Stack stack = new Stack ();


  internal PushbackReader (TextReader reader)
  {
    this.reader = reader;
  }

  internal int Peek ()
  {
    if ( stack.Count > 0 ) return (int)stack.Peek();
    return reader.Peek();
  }

  internal int Read ()
  {
    if ( stack.Count > 0 ) return (int)stack.Pop();
    return reader.Read();
  }

  internal void Unread (int v)
  {
    stack.Push (v);
  }
}

public class LexerException : ApplicationException
{
    public LexerException(String message) : base (message)
    {
    }
}

public class Lexer
{
    protected Token token;
    protected State currentState = State.INITIAL;

    private PushbackReader input;
    private int line;
    private int pos;
    private bool cr;
    private bool eof;
    private StringBuilder text = new StringBuilder();

    protected virtual void Filter()
    {
    }

    public Lexer(TextReader input)
    {
        this.input = new PushbackReader(input);
    }

    public virtual Token Peek()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        return token;
    }

    public virtual Token Next()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected virtual Token GetToken()
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = Lexer.gotoTable[currentState.id()];
        int[] accept = Lexer.accept[currentState.id()];
        text.Length = 0;

        while(true)
        {
            int c = GetChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.Append((char) c);
                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.Length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.Length;
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = New0(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = New1(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = New2(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = New3(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = New4(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = New5(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = New6(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = New7(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = New8(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = New9(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = New10(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = New11(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = New12(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = New13(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = New14(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = New15(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = New16(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = New17(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = New18(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = New19(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = New20(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = New21(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = New22(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = New23(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = New24(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.Length > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    private Token New0(String text, int line, int pos) { return new TProg(text, line, pos); }
    private Token New1(String text, int line, int pos) { return new TLBkt(text, line, pos); }
    private Token New2(String text, int line, int pos) { return new TRBkt(text, line, pos); }
    private Token New3(String text, int line, int pos) { return new TLPar(text, line, pos); }
    private Token New4(String text, int line, int pos) { return new TRPar(text, line, pos); }
    private Token New5(String text, int line, int pos) { return new TLBrace(text, line, pos); }
    private Token New6(String text, int line, int pos) { return new TRBrace(text, line, pos); }
    private Token New7(String text, int line, int pos) { return new TPlus(text, line, pos); }
    private Token New8(String text, int line, int pos) { return new TMinus(text, line, pos); }
    private Token New9(String text, int line, int pos) { return new TSlash(text, line, pos); }
    private Token New10(String text, int line, int pos) { return new TStar(text, line, pos); }
    private Token New11(String text, int line, int pos) { return new TEqual(text, line, pos); }
    private Token New12(String text, int line, int pos) { return new TQMark(text, line, pos); }
    private Token New13(String text, int line, int pos) { return new TBar(text, line, pos); }
    private Token New14(String text, int line, int pos) { return new TArrow(text, line, pos); }
    private Token New15(String text, int line, int pos) { return new TComma(text, line, pos); }
    private Token New16(String text, int line, int pos) { return new TSemicolon(text, line, pos); }
    private Token New17(String text, int line, int pos) { return new TColon(text, line, pos); }
    private Token New18(String text, int line, int pos) { return new TId(text, line, pos); }
    private Token New19(String text, int line, int pos) { return new TChar(text, line, pos); }
    private Token New20(String text, int line, int pos) { return new TNumber(text, line, pos); }
    private Token New21(String text, int line, int pos) { return new THex(text, line, pos); }
    private Token New22(String text, int line, int pos) { return new TString(text, line, pos); }
    private Token New23(String text, int line, int pos) { return new TBlank(text, line, pos); }
    private Token New24(String text, int line, int pos) { return new TComment(text, line, pos); }

    private int GetChar()
    {
        if(eof)
        {
            return -1;
        }

        int result = input.Read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void PushBack(int acceptLength)
    {
        int length = text.Length;
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }
    }


    protected virtual void Unread(Token token)
    {
        String text = token.Text;
        int length = text.Length;

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }

        pos = token.Pos - 1;
        line = token.Line - 1;
    }

    private string GetText(int acceptLength)
    {
        StringBuilder s = new StringBuilder(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.Append(text[i]);
        }

        return s.ToString();
    }

    private static int[][][][] gotoTable = {
      new int[][][] {
        new int[][] {
          new int[] {9, 9, 1},
          new int[] {10, 10, 2},
          new int[] {13, 13, 3},
          new int[] {32, 32, 4},
          new int[] {39, 39, 5},
          new int[] {40, 40, 6},
          new int[] {41, 41, 7},
          new int[] {42, 42, 8},
          new int[] {43, 43, 9},
          new int[] {44, 44, 10},
          new int[] {45, 45, 11},
          new int[] {47, 47, 12},
          new int[] {48, 48, 13},
          new int[] {49, 57, 14},
          new int[] {58, 58, 15},
          new int[] {59, 59, 16},
          new int[] {61, 61, 17},
          new int[] {63, 63, 18},
          new int[] {80, 80, 19},
          new int[] {91, 91, 20},
          new int[] {93, 93, 21},
          new int[] {97, 122, 22},
          new int[] {123, 123, 23},
          new int[] {124, 124, 24},
          new int[] {125, 125, 25},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 9, 1},
          new int[] {10, 10, 26},
          new int[] {13, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {0, 9, 27},
          new int[] {11, 12, 27},
          new int[] {14, 38, 27},
          new int[] {39, 39, 28},
          new int[] {40, 65535, 27},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {62, 62, 29},
        },
        new int[][] {
          new int[] {42, 42, 30},
          new int[] {47, 47, 31},
        },
        new int[][] {
          new int[] {48, 57, 14},
          new int[] {88, 88, 32},
          new int[] {120, 120, 33},
        },
        new int[][] {
          new int[] {48, 57, 14},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {114, 114, 34},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 57, 35},
          new int[] {95, 95, 36},
          new int[] {97, 122, 37},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {0, 9, 38},
          new int[] {11, 12, 38},
          new int[] {14, 38, 38},
          new int[] {39, 39, 39},
          new int[] {40, 65535, 38},
        },
        new int[][] {
          new int[] {39, 39, 40},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {0, 41, 41},
          new int[] {42, 42, 42},
          new int[] {43, 65535, 41},
        },
        new int[][] {
          new int[] {0, 9, 43},
          new int[] {10, 10, 44},
          new int[] {11, 12, 43},
          new int[] {13, 13, 45},
          new int[] {14, 65535, 43},
        },
        new int[][] {
          new int[] {48, 57, 46},
          new int[] {65, 70, 46},
          new int[] {97, 102, 46},
        },
        new int[][] {
          new int[] {48, 102, -34},
        },
        new int[][] {
          new int[] {111, 111, 47},
        },
        new int[][] {
          new int[] {48, 122, -24},
        },
        new int[][] {
          new int[] {97, 122, 48},
        },
        new int[][] {
          new int[] {48, 122, -24},
        },
        new int[][] {
          new int[] {0, 38, -29},
          new int[] {39, 39, 49},
          new int[] {40, 65535, 38},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {0, 65535, -32},
        },
        new int[][] {
          new int[] {0, 41, 50},
          new int[] {42, 42, 42},
          new int[] {43, 46, 50},
          new int[] {47, 47, 51},
          new int[] {48, 65535, 50},
        },
        new int[][] {
          new int[] {0, 65535, -33},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {10, 10, 52},
        },
        new int[][] {
          new int[] {48, 102, -34},
        },
        new int[][] {
          new int[] {103, 103, 53},
        },
        new int[][] {
          new int[] {48, 57, 54},
          new int[] {95, 95, 36},
          new int[] {97, 122, 55},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {0, 41, 56},
          new int[] {42, 42, 57},
          new int[] {43, 65535, 56},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 122, -50},
        },
        new int[][] {
          new int[] {48, 122, -50},
        },
        new int[][] {
          new int[] {0, 65535, -52},
        },
        new int[][] {
          new int[] {0, 41, 50},
          new int[] {42, 42, 57},
          new int[] {43, 65535, -44},
        },
      },
    };

    private static int[][] accept = {
      new int[] {
        -1, 23, 23, 23, 23, -1, 3, 4, 10, 7, 15, 8, 9, 20, 20, 17, 
        16, 11, 12, -1, 1, 2, 18, 5, 13, 6, 23, -1, -1, 14, -1, -1, 
        -1, -1, -1, 18, -1, 18, -1, 19, 19, -1, -1, -1, 24, 24, 21, -1, 
        18, 22, -1, 24, 24, 0, 18, 18, -1, -1, 
      },
    };

    public class State
    {
        public static State INITIAL = new State(0);

        private int _id;

        private State(int _id)
        {
            this._id = _id;
        }

        public int id()
        {
            return _id;
        }
    }
}
}
