/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;

using  Moduino.analysis;

namespace Moduino.node {

public abstract class PGrammar : Node
{
}

public abstract class PStmt : Node
{
}

public abstract class PExp : Node
{
}


public sealed class AGrammar : PGrammar
{
    private TypedList _exp_;

    public AGrammar ()
    {
        this._exp_ = new TypedList(new Exp_Cast(this));
    }

    public AGrammar (
            IList _exp_
    )
    {
        this._exp_ = new TypedList(new Exp_Cast(this));
        this._exp_.Clear();
        this._exp_.AddAll(_exp_);
    }

    public override Object Clone()
    {
        return new AGrammar (
            CloneList (_exp_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAGrammar(this);
    }

    public IList GetExp ()
    {
        return _exp_;
    }

    public void setExp (IList list)
    {
        _exp_.Clear();
        _exp_.AddAll(list);
    }

    public override string ToString()
    {
        return ""
            + ToString (_exp_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _exp_.Contains(child) )
        {
            _exp_.Remove(child);
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        for ( int i = 0; i < _exp_.Count; i++ )
        {
            Node n = (Node)_exp_[i];
            if(n == oldChild)
            {
                if(newChild != null)
                {
                    _exp_[i] = newChild;
                    oldChild.Parent(null);
                    return;
                }

                _exp_.RemoveAt(i);
                oldChild.Parent(null);
                return;
            }
        }
    }

    private class Exp_Cast : Cast
    {
        AGrammar obj;

        internal Exp_Cast (AGrammar obj)
        {
          this.obj = obj;
        }

        public Object Cast(Object o)
        {
            PExp node = (PExp) o;

            if((node.Parent() != null) &&
                (node.Parent() != obj))
            {
                node.Parent().RemoveChild(node);
            }

            if((node.Parent() == null) ||
                (node.Parent() != obj))
            {
                node.Parent(obj);
            }

            return node;
        }

        public Object UnCast(Object o)
        {
            PExp node = (PExp) o;
            node.Parent(null);
            return node;
        }
    }
}
public sealed class AStmt : PStmt
{
    private PExp _exp_;

    public AStmt ()
    {
    }

    public AStmt (
            PExp _exp_
    )
    {
        SetExp (_exp_);
    }

    public override Object Clone()
    {
        return new AStmt (
            (PExp)CloneNode (_exp_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAStmt(this);
    }

    public PExp GetExp ()
    {
        return _exp_;
    }

    public void SetExp (PExp node)
    {
        if(_exp_ != null)
        {
            _exp_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _exp_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_exp_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _exp_ == child )
        {
            _exp_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _exp_ == oldChild )
        {
            SetExp ((PExp) newChild);
            return;
        }
    }

}
public sealed class APlusExp : PExp
{
    private PExp _l_;
    private PExp _r_;

    public APlusExp ()
    {
    }

    public APlusExp (
            PExp _l_,
            PExp _r_
    )
    {
        SetL (_l_);
        SetR (_r_);
    }

    public override Object Clone()
    {
        return new APlusExp (
            (PExp)CloneNode (_l_),
            (PExp)CloneNode (_r_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAPlusExp(this);
    }

    public PExp GetL ()
    {
        return _l_;
    }

    public void SetL (PExp node)
    {
        if(_l_ != null)
        {
            _l_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _l_ = node;
    }
    public PExp GetR ()
    {
        return _r_;
    }

    public void SetR (PExp node)
    {
        if(_r_ != null)
        {
            _r_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _r_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_l_)
            + ToString (_r_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _l_ == child )
        {
            _l_ = null;
            return;
        }
        if ( _r_ == child )
        {
            _r_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _l_ == oldChild )
        {
            SetL ((PExp) newChild);
            return;
        }
        if ( _r_ == oldChild )
        {
            SetR ((PExp) newChild);
            return;
        }
    }

}
public sealed class AMinusExp : PExp
{
    private PExp _l_;
    private PExp _r_;

    public AMinusExp ()
    {
    }

    public AMinusExp (
            PExp _l_,
            PExp _r_
    )
    {
        SetL (_l_);
        SetR (_r_);
    }

    public override Object Clone()
    {
        return new AMinusExp (
            (PExp)CloneNode (_l_),
            (PExp)CloneNode (_r_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAMinusExp(this);
    }

    public PExp GetL ()
    {
        return _l_;
    }

    public void SetL (PExp node)
    {
        if(_l_ != null)
        {
            _l_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _l_ = node;
    }
    public PExp GetR ()
    {
        return _r_;
    }

    public void SetR (PExp node)
    {
        if(_r_ != null)
        {
            _r_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _r_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_l_)
            + ToString (_r_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _l_ == child )
        {
            _l_ = null;
            return;
        }
        if ( _r_ == child )
        {
            _r_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _l_ == oldChild )
        {
            SetL ((PExp) newChild);
            return;
        }
        if ( _r_ == oldChild )
        {
            SetR ((PExp) newChild);
            return;
        }
    }

}
public sealed class ADivExp : PExp
{
    private PExp _l_;
    private PExp _r_;

    public ADivExp ()
    {
    }

    public ADivExp (
            PExp _l_,
            PExp _r_
    )
    {
        SetL (_l_);
        SetR (_r_);
    }

    public override Object Clone()
    {
        return new ADivExp (
            (PExp)CloneNode (_l_),
            (PExp)CloneNode (_r_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseADivExp(this);
    }

    public PExp GetL ()
    {
        return _l_;
    }

    public void SetL (PExp node)
    {
        if(_l_ != null)
        {
            _l_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _l_ = node;
    }
    public PExp GetR ()
    {
        return _r_;
    }

    public void SetR (PExp node)
    {
        if(_r_ != null)
        {
            _r_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _r_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_l_)
            + ToString (_r_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _l_ == child )
        {
            _l_ = null;
            return;
        }
        if ( _r_ == child )
        {
            _r_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _l_ == oldChild )
        {
            SetL ((PExp) newChild);
            return;
        }
        if ( _r_ == oldChild )
        {
            SetR ((PExp) newChild);
            return;
        }
    }

}
public sealed class AMultExp : PExp
{
    private PExp _l_;
    private PExp _r_;

    public AMultExp ()
    {
    }

    public AMultExp (
            PExp _l_,
            PExp _r_
    )
    {
        SetL (_l_);
        SetR (_r_);
    }

    public override Object Clone()
    {
        return new AMultExp (
            (PExp)CloneNode (_l_),
            (PExp)CloneNode (_r_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAMultExp(this);
    }

    public PExp GetL ()
    {
        return _l_;
    }

    public void SetL (PExp node)
    {
        if(_l_ != null)
        {
            _l_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _l_ = node;
    }
    public PExp GetR ()
    {
        return _r_;
    }

    public void SetR (PExp node)
    {
        if(_r_ != null)
        {
            _r_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _r_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_l_)
            + ToString (_r_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _l_ == child )
        {
            _l_ = null;
            return;
        }
        if ( _r_ == child )
        {
            _r_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _l_ == oldChild )
        {
            SetL ((PExp) newChild);
            return;
        }
        if ( _r_ == oldChild )
        {
            SetR ((PExp) newChild);
            return;
        }
    }

}
public sealed class ANumberExp : PExp
{
    private TNumber _number_;

    public ANumberExp ()
    {
    }

    public ANumberExp (
            TNumber _number_
    )
    {
        SetNumber (_number_);
    }

    public override Object Clone()
    {
        return new ANumberExp (
            (TNumber)CloneNode (_number_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseANumberExp(this);
    }

    public TNumber GetNumber ()
    {
        return _number_;
    }

    public void SetNumber (TNumber node)
    {
        if(_number_ != null)
        {
            _number_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _number_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_number_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _number_ == child )
        {
            _number_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _number_ == oldChild )
        {
            SetNumber ((TNumber) newChild);
            return;
        }
    }

}

public sealed class Start : Node
{
    private PGrammar _base_;
    private EOF _eof_;

    public Start()
    {
    }

    public Start(
        PGrammar _base_,
        EOF _eof_)
    {
        SetPGrammar(_base_);
        SetEOF(_eof_);
    }

    public override Object Clone()
    {
        return new Start(
            (PGrammar) CloneNode(_base_),
            (EOF) CloneNode(_eof_));
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseStart(this);
    }

    public PGrammar GetPGrammar()
    {
        return _base_;
    }
    public void SetPGrammar(PGrammar node)
    {
        if(_base_ != null)
        {
            _base_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _base_ = node;
    }

    public EOF GetEOF()
    {
        return _eof_;
    }
    public void SetEOF(EOF node)
    {
        if(_eof_ != null)
        {
            _eof_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _eof_ = node;
    }

    internal override void RemoveChild(Node child)
    {
        if(_base_ == child)
        {
            _base_ = null;
            return;
        }

        if(_eof_ == child)
        {
            _eof_ = null;
            return;
        }
    }
    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if(_base_ == oldChild)
        {
            SetPGrammar((PGrammar) newChild);
            return;
        }

        if(_eof_ == oldChild)
        {
            SetEOF((EOF) newChild);
            return;
        }
    }

    public override string ToString()
    {
        return "" +
            ToString(_base_) +
            ToString(_eof_);
    }
}
}
