/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import java.util.*;
import org.sablecc.sablecc.analysis.*;

public final class AConcat extends PConcat
{
    private final LinkedList _un_exps_ = new TypedLinkedList(new UnExps_Cast());

    public AConcat ()
    {
    }

    public AConcat (
            List _un_exps_
    )
    {
        this._un_exps_.clear();
        this._un_exps_.addAll(_un_exps_);
    }

    public Object clone()
    {
        return new AConcat (
            cloneList (_un_exps_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConcat(this);
    }

    public LinkedList getUnExps ()
    {
        return _un_exps_;
    }

    public void setUnExps (List list)
    {
        _un_exps_.clear();
        _un_exps_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString (_un_exps_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _un_exps_.remove(child))
        {
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _un_exps_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }
    }

    private class UnExps_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PUnExp node = (PUnExp) o;

            if((node.parent() != null) &&
                (node.parent() != AConcat.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AConcat.this))
            {
                node.parent(AConcat.this);
            }

            return node;
        }
    }
}
