/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import java.util.*;
import org.sablecc.sablecc.analysis.*;

public final class ADecChar extends PChar
{
    private TDecChar _dec_char_;

    public ADecChar ()
    {
    }

    public ADecChar (
            TDecChar _dec_char_
    )
    {
        setDecChar (_dec_char_);
    }

    public Object clone()
    {
        return new ADecChar (
            (TDecChar)cloneNode (_dec_char_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecChar(this);
    }

    public TDecChar getDecChar ()
    {
        return _dec_char_;
    }

    public void setDecChar (TDecChar node)
    {
        if(_dec_char_ != null)
        {
            _dec_char_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dec_char_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_dec_char_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _dec_char_ == child )
        {
            _dec_char_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _dec_char_ == oldChild )
        {
            setDecChar ((TDecChar) newChild);
            return;
        }
    }

}
