/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import java.util.*;
import org.sablecc.sablecc.analysis.*;

public final class AHelperDef extends PHelperDef
{
    private TId _id_;
    private PRegExp _reg_exp_;

    public AHelperDef ()
    {
    }

    public AHelperDef (
            TId _id_,
            PRegExp _reg_exp_
    )
    {
        setId (_id_);
        setRegExp (_reg_exp_);
    }

    public Object clone()
    {
        return new AHelperDef (
            (TId)cloneNode (_id_),
            (PRegExp)cloneNode (_reg_exp_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHelperDef(this);
    }

    public TId getId ()
    {
        return _id_;
    }

    public void setId (TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }
    public PRegExp getRegExp ()
    {
        return _reg_exp_;
    }

    public void setRegExp (PRegExp node)
    {
        if(_reg_exp_ != null)
        {
            _reg_exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _reg_exp_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_id_)
            + toString (_reg_exp_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _id_ == child )
        {
            _id_ = null;
            return;
        }
        if ( _reg_exp_ == child )
        {
            _reg_exp_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _id_ == oldChild )
        {
            setId ((TId) newChild);
            return;
        }
        if ( _reg_exp_ == oldChild )
        {
            setRegExp ((PRegExp) newChild);
            return;
        }
    }

}
