/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import java.util.*;
import org.sablecc.sablecc.analysis.*;

public final class AHexChar extends PChar
{
    private THexChar _hex_char_;

    public AHexChar ()
    {
    }

    public AHexChar (
            THexChar _hex_char_
    )
    {
        setHexChar (_hex_char_);
    }

    public Object clone()
    {
        return new AHexChar (
            (THexChar)cloneNode (_hex_char_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHexChar(this);
    }

    public THexChar getHexChar ()
    {
        return _hex_char_;
    }

    public void setHexChar (THexChar node)
    {
        if(_hex_char_ != null)
        {
            _hex_char_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _hex_char_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_hex_char_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _hex_char_ == child )
        {
            _hex_char_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _hex_char_ == oldChild )
        {
            setHexChar ((THexChar) newChild);
            return;
        }
    }

}
