/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.node;

import java.util.*;
import org.sablecc.sablecc.analysis.*;

public final class AQMarkUnOp extends PUnOp
{
    private TQMark _q_mark_;

    public AQMarkUnOp ()
    {
    }

    public AQMarkUnOp (
            TQMark _q_mark_
    )
    {
        setQMark (_q_mark_);
    }

    public Object clone()
    {
        return new AQMarkUnOp (
            (TQMark)cloneNode (_q_mark_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAQMarkUnOp(this);
    }

    public TQMark getQMark ()
    {
        return _q_mark_;
    }

    public void setQMark (TQMark node)
    {
        if(_q_mark_ != null)
        {
            _q_mark_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _q_mark_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_q_mark_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _q_mark_ == child )
        {
            _q_mark_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _q_mark_ == oldChild )
        {
            setQMark ((TQMark) newChild);
            return;
        }
    }

}
