/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class AAttribXpathElem extends PXpathElem
{
    private TXattrib _xattrib_;

    public AAttribXpathElem ()
    {
    }

    public AAttribXpathElem (
            TXattrib _xattrib_
    )
    {
        setXattrib (_xattrib_);
    }

    public Object clone()
    {
        return new AAttribXpathElem (
            (TXattrib)cloneNode (_xattrib_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttribXpathElem(this);
    }

    public TXattrib getXattrib ()
    {
        return _xattrib_;
    }

    public void setXattrib (TXattrib node)
    {
        if(_xattrib_ != null)
        {
            _xattrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xattrib_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_xattrib_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _xattrib_ == child )
        {
            _xattrib_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _xattrib_ == oldChild )
        {
            setXattrib ((TXattrib) newChild);
            return;
        }
    }

}
