/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class ACurrentXpathElem extends PXpathElem
{


    public ACurrentXpathElem (
    )
    {
    }

    public Object clone()
    {
        return new ACurrentXpathElem (
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACurrentXpathElem(this);
    }


    public String toString()
    {
        return ""
        ;
    }

    void removeChild(Node child)
    {
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

}
