/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class ADataStatement extends PStatement
{
    private TData _data_;

    public ADataStatement ()
    {
    }

    public ADataStatement (
            TData _data_
    )
    {
        setData (_data_);
    }

    public Object clone()
    {
        return new ADataStatement (
            (TData)cloneNode (_data_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADataStatement(this);
    }

    public TData getData ()
    {
        return _data_;
    }

    public void setData (TData node)
    {
        if(_data_ != null)
        {
            _data_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _data_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_data_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _data_ == child )
        {
            _data_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _data_ == oldChild )
        {
            setData ((TData) newChild);
            return;
        }
    }

}
