/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class AForeachStatement extends PStatement
{
    private TIdentifier _var_;
    private PXpathExpr _xpath_;
    private final LinkedList _statement_ = new TypedLinkedList(new Statement_Cast());

    public AForeachStatement ()
    {
    }

    public AForeachStatement (
            TIdentifier _var_,
            PXpathExpr _xpath_,
            List _statement_
    )
    {
        setVar (_var_);
        setXpath (_xpath_);
        this._statement_.clear();
        this._statement_.addAll(_statement_);
    }

    public Object clone()
    {
        return new AForeachStatement (
            (TIdentifier)cloneNode (_var_),
            (PXpathExpr)cloneNode (_xpath_),
            cloneList (_statement_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForeachStatement(this);
    }

    public TIdentifier getVar ()
    {
        return _var_;
    }

    public void setVar (TIdentifier node)
    {
        if(_var_ != null)
        {
            _var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _var_ = node;
    }
    public PXpathExpr getXpath ()
    {
        return _xpath_;
    }

    public void setXpath (PXpathExpr node)
    {
        if(_xpath_ != null)
        {
            _xpath_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xpath_ = node;
    }
    public LinkedList getStatement ()
    {
        return _statement_;
    }

    public void setStatement (List list)
    {
        _statement_.clear();
        _statement_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString (_var_)
            + toString (_xpath_)
            + toString (_statement_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _var_ == child )
        {
            _var_ = null;
            return;
        }
        if ( _xpath_ == child )
        {
            _xpath_ = null;
            return;
        }
        if ( _statement_.remove(child))
        {
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _var_ == oldChild )
        {
            setVar ((TIdentifier) newChild);
            return;
        }
        if ( _xpath_ == oldChild )
        {
            setXpath ((PXpathExpr) newChild);
            return;
        }
        for(ListIterator i = _statement_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }
    }

    private class Statement_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PStatement node = (PStatement) o;

            if((node.parent() != null) &&
                (node.parent() != AForeachStatement.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AForeachStatement.this))
            {
                node.parent(AForeachStatement.this);
            }

            return node;
        }
    }
}
