/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class AFunctionXpathExpr extends PXpathExpr
{
    private TXname _name_;
    private final LinkedList _args_ = new TypedLinkedList(new Args_Cast());

    public AFunctionXpathExpr ()
    {
    }

    public AFunctionXpathExpr (
            TXname _name_,
            List _args_
    )
    {
        setName (_name_);
        this._args_.clear();
        this._args_.addAll(_args_);
    }

    public Object clone()
    {
        return new AFunctionXpathExpr (
            (TXname)cloneNode (_name_),
            cloneList (_args_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionXpathExpr(this);
    }

    public TXname getName ()
    {
        return _name_;
    }

    public void setName (TXname node)
    {
        if(_name_ != null)
        {
            _name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _name_ = node;
    }
    public LinkedList getArgs ()
    {
        return _args_;
    }

    public void setArgs (List list)
    {
        _args_.clear();
        _args_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString (_name_)
            + toString (_args_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _name_ == child )
        {
            _name_ = null;
            return;
        }
        if ( _args_.remove(child))
        {
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _name_ == oldChild )
        {
            setName ((TXname) newChild);
            return;
        }
        for(ListIterator i = _args_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }
    }

    private class Args_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PXpathExpr node = (PXpathExpr) o;

            if((node.parent() != null) &&
                (node.parent() != AFunctionXpathExpr.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AFunctionXpathExpr.this))
            {
                node.parent(AFunctionXpathExpr.this);
            }

            return node;
        }
    }
}
