/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class AIattribExpr extends PExpr
{
    private TIattrib _iattrib_;

    public AIattribExpr ()
    {
    }

    public AIattribExpr (
            TIattrib _iattrib_
    )
    {
        setIattrib (_iattrib_);
    }

    public Object clone()
    {
        return new AIattribExpr (
            (TIattrib)cloneNode (_iattrib_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIattribExpr(this);
    }

    public TIattrib getIattrib ()
    {
        return _iattrib_;
    }

    public void setIattrib (TIattrib node)
    {
        if(_iattrib_ != null)
        {
            _iattrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _iattrib_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_iattrib_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _iattrib_ == child )
        {
            _iattrib_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _iattrib_ == oldChild )
        {
            setIattrib ((TIattrib) newChild);
            return;
        }
    }

}
