/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class ANameXpathElem extends PXpathElem
{
    private TXname _xname_;

    public ANameXpathElem ()
    {
    }

    public ANameXpathElem (
            TXname _xname_
    )
    {
        setXname (_xname_);
    }

    public Object clone()
    {
        return new ANameXpathElem (
            (TXname)cloneNode (_xname_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANameXpathElem(this);
    }

    public TXname getXname ()
    {
        return _xname_;
    }

    public void setXname (TXname node)
    {
        if(_xname_ != null)
        {
            _xname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xname_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_xname_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _xname_ == child )
        {
            _xname_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _xname_ == oldChild )
        {
            setXname ((TXname) newChild);
            return;
        }
    }

}
