/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class ANumberXpathExpr extends PXpathExpr
{
    private TXnumber _xnumber_;

    public ANumberXpathExpr ()
    {
    }

    public ANumberXpathExpr (
            TXnumber _xnumber_
    )
    {
        setXnumber (_xnumber_);
    }

    public Object clone()
    {
        return new ANumberXpathExpr (
            (TXnumber)cloneNode (_xnumber_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumberXpathExpr(this);
    }

    public TXnumber getXnumber ()
    {
        return _xnumber_;
    }

    public void setXnumber (TXnumber node)
    {
        if(_xnumber_ != null)
        {
            _xnumber_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xnumber_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_xnumber_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _xnumber_ == child )
        {
            _xnumber_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _xnumber_ == oldChild )
        {
            setXnumber ((TXnumber) newChild);
            return;
        }
    }

}
