/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class AOutputStatement extends PStatement
{
    private PExpr _expr_;
    private final LinkedList _statement_ = new TypedLinkedList(new Statement_Cast());

    public AOutputStatement ()
    {
    }

    public AOutputStatement (
            PExpr _expr_,
            List _statement_
    )
    {
        setExpr (_expr_);
        this._statement_.clear();
        this._statement_.addAll(_statement_);
    }

    public Object clone()
    {
        return new AOutputStatement (
            (PExpr)cloneNode (_expr_),
            cloneList (_statement_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOutputStatement(this);
    }

    public PExpr getExpr ()
    {
        return _expr_;
    }

    public void setExpr (PExpr node)
    {
        if(_expr_ != null)
        {
            _expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expr_ = node;
    }
    public LinkedList getStatement ()
    {
        return _statement_;
    }

    public void setStatement (List list)
    {
        _statement_.clear();
        _statement_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString (_expr_)
            + toString (_statement_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _expr_ == child )
        {
            _expr_ = null;
            return;
        }
        if ( _statement_.remove(child))
        {
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _expr_ == oldChild )
        {
            setExpr ((PExpr) newChild);
            return;
        }
        for(ListIterator i = _statement_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }
    }

    private class Statement_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PStatement node = (PStatement) o;

            if((node.parent() != null) &&
                (node.parent() != AOutputStatement.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AOutputStatement.this))
            {
                node.parent(AOutputStatement.this);
            }

            return node;
        }
    }
}
