/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class AScript extends PScript
{
    private final LinkedList _statement_ = new TypedLinkedList(new Statement_Cast());

    public AScript ()
    {
    }

    public AScript (
            List _statement_
    )
    {
        this._statement_.clear();
        this._statement_.addAll(_statement_);
    }

    public Object clone()
    {
        return new AScript (
            cloneList (_statement_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAScript(this);
    }

    public LinkedList getStatement ()
    {
        return _statement_;
    }

    public void setStatement (List list)
    {
        _statement_.clear();
        _statement_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString (_statement_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _statement_.remove(child))
        {
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _statement_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }
    }

    private class Statement_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PStatement node = (PStatement) o;

            if((node.parent() != null) &&
                (node.parent() != AScript.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AScript.this))
            {
                node.parent(AScript.this);
            }

            return node;
        }
    }
}
