/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class ASetStatement extends PStatement
{
    private final LinkedList _args_ = new TypedLinkedList(new Args_Cast());

    public ASetStatement ()
    {
    }

    public ASetStatement (
            List _args_
    )
    {
        this._args_.clear();
        this._args_.addAll(_args_);
    }

    public Object clone()
    {
        return new ASetStatement (
            cloneList (_args_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASetStatement(this);
    }

    public LinkedList getArgs ()
    {
        return _args_;
    }

    public void setArgs (List list)
    {
        _args_.clear();
        _args_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString (_args_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _args_.remove(child))
        {
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _args_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }
    }

    private class Args_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PArg node = (PArg) o;

            if((node.parent() != null) &&
                (node.parent() != ASetStatement.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ASetStatement.this))
            {
                node.parent(ASetStatement.this);
            }

            return node;
        }
    }
}
