/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class AXpathPathElem extends PXpathPathElem
{
    private PXpathSeparator _separator_;
    private PXpathElem _elem_;
    private PXpathExpr _condition_;

    public AXpathPathElem ()
    {
    }

    public AXpathPathElem (
            PXpathSeparator _separator_,
            PXpathElem _elem_,
            PXpathExpr _condition_
    )
    {
        setSeparator (_separator_);
        setElem (_elem_);
        setCondition (_condition_);
    }

    public Object clone()
    {
        return new AXpathPathElem (
            (PXpathSeparator)cloneNode (_separator_),
            (PXpathElem)cloneNode (_elem_),
            (PXpathExpr)cloneNode (_condition_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAXpathPathElem(this);
    }

    public PXpathSeparator getSeparator ()
    {
        return _separator_;
    }

    public void setSeparator (PXpathSeparator node)
    {
        if(_separator_ != null)
        {
            _separator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _separator_ = node;
    }
    public PXpathElem getElem ()
    {
        return _elem_;
    }

    public void setElem (PXpathElem node)
    {
        if(_elem_ != null)
        {
            _elem_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _elem_ = node;
    }
    public PXpathExpr getCondition ()
    {
        return _condition_;
    }

    public void setCondition (PXpathExpr node)
    {
        if(_condition_ != null)
        {
            _condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _condition_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_separator_)
            + toString (_elem_)
            + toString (_condition_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _separator_ == child )
        {
            _separator_ = null;
            return;
        }
        if ( _elem_ == child )
        {
            _elem_ = null;
            return;
        }
        if ( _condition_ == child )
        {
            _condition_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _separator_ == oldChild )
        {
            setSeparator ((PXpathSeparator) newChild);
            return;
        }
        if ( _elem_ == oldChild )
        {
            setElem ((PXpathElem) newChild);
            return;
        }
        if ( _condition_ == oldChild )
        {
            setCondition ((PXpathExpr) newChild);
            return;
        }
    }

}
