/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import java.util.*;
import org.sablecc.sablecc.xss2.analysis.*;

public final class AXpathExpr extends PExpr
{
    private PXpathExpr _xpath_expr_;

    public AXpathExpr ()
    {
    }

    public AXpathExpr (
            PXpathExpr _xpath_expr_
    )
    {
        setXpathExpr (_xpath_expr_);
    }

    public Object clone()
    {
        return new AXpathExpr (
            (PXpathExpr)cloneNode (_xpath_expr_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAXpathExpr(this);
    }

    public PXpathExpr getXpathExpr ()
    {
        return _xpath_expr_;
    }

    public void setXpathExpr (PXpathExpr node)
    {
        if(_xpath_expr_ != null)
        {
            _xpath_expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xpath_expr_ = node;
    }

    public String toString()
    {
        return ""
            + toString (_xpath_expr_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _xpath_expr_ == child )
        {
            _xpath_expr_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if ( _xpath_expr_ == oldChild )
        {
            setXpathExpr ((PXpathExpr) newChild);
            return;
        }
    }

}
