/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TCmdEnd extends Token
{
    public TCmdEnd()
    {
        super.setText("-]");
    }

    public TCmdEnd(int line, int pos)
    {
        super.setText("-]");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TCmdEnd(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCmdEnd(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TCmdEnd text.");
    }
}
