/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TCmdStart extends Token
{
    public TCmdStart()
    {
        super.setText("[-");
    }

    public TCmdStart(int line, int pos)
    {
        super.setText("[-");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TCmdStart(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCmdStart(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TCmdStart text.");
    }
}
