/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TIxpathStart extends Token
{
    public TIxpathStart()
    {
        super.setText("${");
    }

    public TIxpathStart(int line, int pos)
    {
        super.setText("${");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TIxpathStart(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIxpathStart(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TIxpathStart text.");
    }
}
