/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXand extends Token
{
    public TXand()
    {
        super.setText("and");
    }

    public TXand(int line, int pos)
    {
        super.setText("and");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXand(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXand(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXand text.");
    }
}
