/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXdiv extends Token
{
    public TXdiv()
    {
        super.setText("div");
    }

    public TXdiv(int line, int pos)
    {
        super.setText("div");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXdiv(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXdiv(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXdiv text.");
    }
}
