/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXequals extends Token
{
    public TXequals()
    {
        super.setText("=");
    }

    public TXequals(int line, int pos)
    {
        super.setText("=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXequals(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXequals(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXequals text.");
    }
}
