/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXgreaterOrEqual extends Token
{
    public TXgreaterOrEqual()
    {
        super.setText(">=");
    }

    public TXgreaterOrEqual(int line, int pos)
    {
        super.setText(">=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXgreaterOrEqual(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXgreaterOrEqual(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXgreaterOrEqual text.");
    }
}
