/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXlBrace extends Token
{
    public TXlBrace()
    {
        super.setText("[");
    }

    public TXlBrace(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXlBrace(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXlBrace(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXlBrace text.");
    }
}
