/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXlessOrEqual extends Token
{
    public TXlessOrEqual()
    {
        super.setText("<=");
    }

    public TXlessOrEqual(int line, int pos)
    {
        super.setText("<=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXlessOrEqual(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXlessOrEqual(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXlessOrEqual text.");
    }
}
