/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXless extends Token
{
    public TXless()
    {
        super.setText("<");
    }

    public TXless(int line, int pos)
    {
        super.setText("<");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXless(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXless(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXless text.");
    }
}
