/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXlPar extends Token
{
    public TXlPar()
    {
        super.setText("(");
    }

    public TXlPar(int line, int pos)
    {
        super.setText("(");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXlPar(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXlPar(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXlPar text.");
    }
}
