/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXmul extends Token
{
    public TXmul()
    {
        super.setText("*");
    }

    public TXmul(int line, int pos)
    {
        super.setText("*");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXmul(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXmul(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXmul text.");
    }
}
