/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXparent extends Token
{
    public TXparent()
    {
        super.setText("..");
    }

    public TXparent(int line, int pos)
    {
        super.setText("..");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXparent(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXparent(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXparent text.");
    }
}
