/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXpathStart extends Token
{
    public TXpathStart()
    {
        super.setText("{");
    }

    public TXpathStart(int line, int pos)
    {
        super.setText("{");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXpathStart(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXpathStart(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXpathStart text.");
    }
}
