/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXrBrace extends Token
{
    public TXrBrace()
    {
        super.setText("]");
    }

    public TXrBrace(int line, int pos)
    {
        super.setText("]");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXrBrace(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXrBrace(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXrBrace text.");
    }
}
