/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXsepOne extends Token
{
    public TXsepOne()
    {
        super.setText("/");
    }

    public TXsepOne(int line, int pos)
    {
        super.setText("/");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXsepOne(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXsepOne(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXsepOne text.");
    }
}
