/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.xss2.node;

import org.sablecc.sablecc.xss2.analysis.*;

public final class TXsub extends Token
{
    public TXsub()
    {
        super.setText("-");
    }

    public TXsub(int line, int pos)
    {
        super.setText("-");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXsub(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXsub(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXsub text.");
    }
}
